### ISSUE TITLE
Error Fakeinventorys

### ISSUE THREAD

**Issue by PocketMiner92** [GommeAWM/Auction#2]
[36m12:58:03[m [[m[1;31mERROR[m[m] Das Event "cn.nukkit.event.server.DataPacketSendEvent" konnte nicht zu "FakeInventories v1.0.3": null in Zeile com.nukkitx.fakeinventories.FakeInventoriesListener weitergegeben werden

cn.nukkit.utils.EventException: null

at cn.nukkit.plugin.MethodEventExecutor.execute(MethodEventExecutor.java:35) ~[nukkit-stable.jar:?]

at cn.nukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:60) ~[nukkit-stable.jar:?]

at cn.nukkit.plugin.PluginManager.callEvent(PluginManager.java:572) [nukkit-stable.jar:?]

at cn.nukkit.Player.dataPacket(Player.java:1171) [nukkit-stable.jar:?]

at com.nukkitx.fakeinventories.inventory.ChestFakeInventory.placeChest(ChestFakeInventory.java:60) [Invsee.jar:?]

at com.nukkitx.fakeinventories.inventory.DoubleChestFakeInventory.onOpenBlock(DoubleChestFakeInventory.java:50) [Invsee.jar:?]

at com.nukkitx.fakeinventories.inventory.DoubleChestFakeInventory.onOpen(DoubleChestFakeInventory.java:37) [Invsee.jar:?]

at cn.nukkit.inventory.BaseInventory.open(BaseInventory.java:433) [nukkit-stable.jar:?]

at cn.nukkit.Player.addWindow(Player.java:5488) [nukkit-stable.jar:?]

at cn.nukkit.Player.addWindow(Player.java:5468) [nukkit-stable.jar:?]

at cn.nukkit.Player.addWindow(Player.java:5464) [nukkit-stable.jar:?]

at cn.nukkit.Player.addWindow(Player.java:5460) [nukkit-stable.jar:?]

at getmc.Command.AucCMD.openAction(AucCMD.java:212) [GetAuction-1.0-SNAPSHOT.jar:?]

at getmc.Command.AucCMD.execute(AucCMD.java:47) [GetAuction-1.0-SNAPSHOT.jar:?]

at cn.nukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:259) [nukkit-stable.jar:?]

at cn.nukkit.Server.dispatchCommand(Server.java:964) [nukkit-stable.jar:?]

at getmc.Listener.InventoryTransactionListener.interact(InventoryTransactionListener.java:669) [GetAuction-1.0-SNAPSHOT.jar:?]

at getmc.Listener.InventoryTransactionListener.onChest(InventoryTransactionListener.java:146) [GetAuction-1.0-SNAPSHOT.jar:?]

at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_212]

at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_212]

at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_212]

at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_212]

at cn.nukkit.plugin.MethodEventExecutor.execute(MethodEventExecutor.java:30) [nukkit-stable.jar:?]

at cn.nukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:60) [nukkit-stable.jar:?]

at cn.nukkit.plugin.PluginManager.callEvent(PluginManager.java:572) [nukkit-stable.jar:?]

at cn.nukkit.inventory.transaction.InventoryTransaction.callExecuteEvent(InventoryTransaction.java:170) [nukkit-stable.jar:?]

at cn.nukkit.inventory.transaction.InventoryTransaction.execute(InventoryTransaction.java:217) [nukkit-stable.jar:?]

at cn.nukkit.Player.handleDataPacket(Player.java:3684) [nukkit-stable.jar:?]

at cn.nukkit.network.RakNetInterface.process(RakNetInterface.java:129) [nukkit-stable.jar:?]

at cn.nukkit.network.Network.processInterfaces(Network.java:170) [nukkit-stable.jar:?]

at cn.nukkit.Server.tick(Server.java:1363) [nukkit-stable.jar:?]

at cn.nukkit.Server.tickProcessor(Server.java:1146) [nukkit-stable.jar:?]

at cn.nukkit.Server.start(Server.java:1106) [nukkit-stable.jar:?]

at cn.nukkit.Server.<init>(Server.java:778) [nukkit-stable.jar:?]

at cn.nukkit.Nukkit.main(Nukkit.java:200) [nukkit-stable.jar:?]

Caused by: java.lang.IllegalAccessError: tried to access field com.nukkitx.fakeinventories.inventory.FakeInventory.open from class com.nukkitx.fakeinventories.inventory.FakeInventories

at com.nukkitx.fakeinventories.inventory.FakeInventories.getFakeInventoryPositions(FakeInventories.java:11) ~[?:?]

at com.nukkitx.fakeinventories.FakeInventoriesListener.onPacketSend(FakeInventoriesListener.java:32) ~[?:?]

at sun.reflect.GeneratedMethodAccessor17.invoke(Unknown Source) ~[?:?]

at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_212]

at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_212]

at cn.nukkit.plugin.MethodEventExecutor.execute(MethodEventExecutor.java:30) ~[nukkit-stable.jar:?]

... 34 more

[36m12:58:03[m [[m[1;31mERROR[m[m] Das Event "cn.nukkit.event.server.DataPacketSendEvent" konnte nicht zu "FakeInventories v1.0.3": null in Zeile com.nukkitx.fakeinventories.FakeInventoriesListener weitergegeben werden

cn.nukkit.utils.EventException: null

at cn.nukkit.plugin.MethodEventExecutor.execute(MethodEventExecutor.java:35) ~[nukkit-stable.jar:?]

at cn.nukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:60) ~[nukkit-stable.jar:?]

at cn.nukkit.plugin.PluginManager.callEvent(PluginManager.java:572) [nukkit-stable.jar:?]

at cn.nukkit.Player.dataPacket(Player.java:1171) [nukkit-stable.jar:?]

at com.nukkitx.fakeinventories.inventory.ChestFakeInventory.placeChest(ChestFakeInventory.java:60) [Invsee.jar:?]

at com.nukkitx.fakeinventories.inventory.DoubleChestFakeInventory.onOpenBlock(DoubleChestFakeInventory.java:51) [Invsee.jar:?]

at com.nukkitx.fakeinventories.inventory.DoubleChestFakeInventory.onOpen(DoubleChestFakeInventory.java:37) [Invsee.jar:?]

at cn.nukkit.inventory.BaseInventory.open(BaseInventory.java:433) [nukkit-stable.jar:?]

at cn.nukkit.Player.addWindow(Player.java:5488) [nukkit-stable.jar:?]

at cn.nukkit.Player.addWindow(Player.java:5468) [nukkit-stable.jar:?]

at cn.nukkit.Player.addWindow(Player.java:5464) [nukkit-stable.jar:?]

at cn.nukkit.Player.addWindow(Player.java:5460) [nukkit-stable.jar:?]

at getmc.Command.AucCMD.openAction(AucCMD.java:212) [GetAuction-1.0-SNAPSHOT.jar:?]

at getmc.Command.AucCMD.execute(AucCMD.java:47) [GetAuction-1.0-SNAPSHOT.jar:?]

at cn.nukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:259) [nukkit-stable.jar:?]

at cn.nukkit.Server.dispatchCommand(Server.java:964) [nukkit-stable.jar:?]

at getmc.Listener.InventoryTransactionListener.interact(InventoryTransactionListener.java:669) [GetAuction-1.0-SNAPSHOT.jar:?]

at getmc.Listener.InventoryTransactionListener.onChest(InventoryTransactionListener.java:146) [GetAuction-1.0-SNAPSHOT.jar:?]

at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_212]

at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_212]

at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_212]

at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_212]

at cn.nukkit.plugin.MethodEventExecutor.execute(MethodEventExecutor.java:30) [nukkit-stable.jar:?]

at cn.nukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:60) [nukkit-stable.jar:?]

at cn.nukkit.plugin.PluginManager.callEvent(PluginManager.java:572) [nukkit-stable.jar:?]

at cn.nukkit.inventory.transaction.InventoryTransaction.callExecuteEvent(InventoryTransaction.java:170) [nukkit-stable.jar:?]

at cn.nukkit.inventory.transaction.InventoryTransaction.execute(InventoryTransaction.java:217) [nukkit-stable.jar:?]

at cn.nukkit.Player.handleDataPacket(Player.java:3684) [nukkit-stable.jar:?]

at cn.nukkit.network.RakNetInterface.process(RakNetInterface.java:129) [nukkit-stable.jar:?]

at cn.nukkit.network.Network.processInterfaces(Network.java:170) [nukkit-stable.jar:?]

at cn.nukkit.Server.tick(Server.java:1363) [nukkit-stable.jar:?]

at cn.nukkit.Server.tickProcessor(Server.java:1146) [nukkit-stable.jar:?]

at cn.nukkit.Server.start(Server.java:1106) [nukkit-stable.jar:?]

at cn.nukkit.Server.<init>(Server.java:778) [nukkit-stable.jar:?]

at cn.nukkit.Nukkit.main(Nukkit.java:200) [nukkit-stable.jar:?]

Caused by: java.lang.IllegalAccessError: tried to access field com.nukkitx.fakeinventories.inventory.FakeInventory.open from class com.nukkitx.fakeinventories.inventory.FakeInventories

at com.nukkitx.fakeinventories.inventory.FakeInventories.getFakeInventoryPositions(FakeInventories.java:11) ~[?:?]

at com.nukkitx.fakeinventories.FakeInventoriesListener.onPacketSend(FakeInventoriesListener.java:32) ~[?:?]

at sun.reflect.GeneratedMethodAccessor17.invoke(Unknown Source) ~[?:?]

at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_212]

at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_212]

at cn.nukkit.plugin.MethodEventExecutor.execute(MethodEventExecutor.java:30) ~[nukkit-stable.jar:?]

... 34 more

[36m12:58:10[m [[m[1;31mERROR[m[m] Das Event "cn.nukkit.event.server.DataPacketSendEvent" konnte nicht zu "FakeInventories v1.0.3": null in Zeile com.nukkitx.fakeinventories.FakeInventoriesListener weitergegeben werden

cn.nukkit.utils.EventException: null

at cn.nukkit.plugin.MethodEventExecutor.execute(MethodEventExecutor.java:35) ~[nukkit-stable.jar:?]

at cn.nukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:60) ~[nukkit-stable.jar:?]

at cn.nukkit.plugin.PluginManager.callEvent(PluginManager.java:572) ~[nukkit-stable.jar:?]

at cn.nukkit.Player.dataPacket(Player.java:1171) ~[nukkit-stable.jar:?]

at com.nukkitx.fakeinventories.inventory.FakeInventory.lambda$onClose$0(FakeInventory.java:94) ~[?:?]

at cn.nukkit.scheduler.TaskHandler.run(TaskHandler.java:100) [nukkit-stable.jar:?]

at cn.nukkit.scheduler.ServerScheduler.runTasks(ServerScheduler.java:298) [nukkit-stable.jar:?]

at cn.nukkit.scheduler.ServerScheduler.mainThreadHeartbeat(ServerScheduler.java:279) [nukkit-stable.jar:?]

at cn.nukkit.Server.tick(Server.java:1371) [nukkit-stable.jar:?]

at cn.nukkit.Server.tickProcessor(Server.java:1146) [nukkit-stable.jar:?]

at cn.nukkit.Server.start(Server.java:1106) [nukkit-stable.jar:?]

at cn.nukkit.Server.<init>(Server.java:778) [nukkit-stable.jar:?]

at cn.nukkit.Nukkit.main(Nukkit.java:200) [nukkit-stable.jar:?]

Caused by: java.lang.IllegalAccessError: tried to access field com.nukkitx.fakeinventories.inventory.FakeInventory.open from class com.nukkitx.fakeinventories.inventory.FakeInventories

at com.nukkitx.fakeinventories.inventory.FakeInventories.getFakeInventoryPositions(FakeInventories.java:11) ~[?:?]

at com.nukkitx.fakeinventories.FakeInventoriesListener.onPacketSend(FakeInventoriesListener.java:32) ~[?:?]

at sun.reflect.GeneratedMethodAccessor17.invoke(Unknown Source) ~[?:?]

at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_212]

at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_212]

at cn.nukkit.plugin.MethodEventExecutor.execute(MethodEventExecutor.java:30) ~[nukkit-stable.jar:?]

... 12 more

[36m12:58:10[m [[m[1;31mERROR[m[m] Das Event "cn.nukkit.event.server.DataPacketSendEvent" konnte nicht zu "FakeInventories v1.0.3": null in Zeile com.nukkitx.fakeinventories.FakeInventoriesListener weitergegeben werden

cn.nukkit.utils.EventException: null

at cn.nukkit.plugin.MethodEventExecutor.execute(MethodEventExecutor.java:35) ~[nukkit-stable.jar:?]

at cn.nukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:60) ~[nukkit-stable.jar:?]

at cn.nukkit.plugin.PluginManager.callEvent(PluginManager.java:572) ~[nukkit-stable.jar:?]

at cn.nukkit.Player.dataPacket(Player.java:1171) ~[nukkit-stable.jar:?]

at com.nukkitx.fakeinventories.inventory.FakeInventory.lambda$onClose$0(FakeInventory.java:94) ~[?:?]

at cn.nukkit.scheduler.TaskHandler.run(TaskHandler.java:100) [nukkit-stable.jar:?]

at cn.nukkit.scheduler.ServerScheduler.runTasks(ServerScheduler.java:298) [nukkit-stable.jar:?]

at cn.nukkit.scheduler.ServerScheduler.mainThreadHeartbeat(ServerScheduler.java:279) [nukkit-stable.jar:?]

at cn.nukkit.Server.tick(Server.java:1371) [nukkit-stable.jar:?]

at cn.nukkit.Server.tickProcessor(Server.java:1146) [nukkit-stable.jar:?]

at cn.nukkit.Server.start(Server.java:1106) [nukkit-stable.jar:?]

at cn.nukkit.Server.<init>(Server.java:778) [nukkit-stable.jar:?]

at cn.nukkit.Nukkit.main(Nukkit.java:200) [nukkit-stable.jar:?]

Caused by: java.lang.IllegalAccessError: tried to access field com.nukkitx.fakeinventories.inventory.FakeInventory.open from class com.nukkitx.fakeinventories.inventory.FakeInventories

at com.nukkitx.fakeinventories.inventory.FakeInventories.getFakeInventoryPositions(FakeInventories.java:11) ~[?:?]

at com.nukkitx.fakeinventories.FakeInventoriesListener.onPacketSend(FakeInventoriesListener.java:32) ~[?:?]

at sun.reflect.GeneratedMethodAccessor17.invoke(Unknown Source) ~[?:?]

at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_212]

at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_212]

at cn.nukkit.plugin.MethodEventExecutor.execute(MethodEventExecutor.java:30) ~[nukkit-stable.jar:?]

... 12 more

**Comment by GommeAWM** [comment]
Do you have plugin FakeInventories on your Server?

**Comment by PocketMiner92** [comment]
Yes

**Comment by PocketMiner92** [comment]
This Bug is reported to Nukkit too.
But noone fix this.

**Comment by GommeAWM** [comment]
Do you use NukkitPetteriM1Edition core?

**Comment by GommeAWM** [comment]
because on this core you can get Problems with FakeInventories, if you want you can try to change core to the normal Nukkit core

**Comment by PocketMiner92** [comment]
I use Powernukkit

Its a Problem by Powernukkit?

**Comment by GommeAWM** [comment]
oh, this plugin is for nukkit not really for PowerNukkit

**Comment by GommeAWM** [comment]
It looks like we've found the problem

**Comment by PocketMiner92** [comment]
Oh man.
OK thanks for youre Help.
Can you create a Powernukkit Version?
Because many Users use Powernukkit.
It Supports More features than Nukkit.

**Comment by GommeAWM** [comment]
I'll try, but that would take time.
